<a href="https://colab.research.google.com/github/Gugo-le/school_record_/blob/colab-%EC%8B%A4%EC%8A%B5/TFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

train
test


In [3]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>


In [4]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [5]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [6]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='/root/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author    =

In [7]:
mnist = tf.keras.datasets.fashion_mnist

(training_images, training_labels), (test_images, test_labels) = \
    mnist.load_data()

In [8]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.as_numpy(tfds.load('fashion_mnist',
                            split = ['train', 'test'],
                            batch_size=-1, # 모든 데이터 가져옴
                            as_supervised=True)) #(입력, 레이블)로 구성된 투플이 반환된다.

In [9]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.load('fashion_mnist',
              split = ['train', 'test'],
              batch_size=-1,
              as_supervised=True)

training_images = tf.cast(training_images, tf.float32) / 255.0
test_images = tf.cast(test_images, tf.float32) / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7611 - loss: 0.6726
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8543 - loss: 0.4048
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8645 - loss: 0.3673
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8726 - loss: 0.3462
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8808 - loss: 0.3250


In [10]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu',
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adam', loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_batches, epochs=10)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


103/103 ━━━━━━━━━━━━━━━━━━━━ 106s 990ms/step - accuracy: 0.6920 - loss: 3.5723
Epoch 2/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 132s 904ms/step - accuracy: 0.9518 - loss: 0.1660
Epoch 3/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 140s 890ms/step - accuracy: 0.9162 - loss: 0.1987
Epoch 4/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 94s 913ms/step - accuracy: 0.9871 - loss: 0.0407
Epoch 5/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 93s 903ms/step - accuracy: 0.9875 - loss: 0.0234
Epoch 6/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 142s 900ms/step - accuracy: 1.0000 - loss: 0.0016
Epoch 7/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 145s 921ms/step - accuracy: 1.0000 - loss: 3.5357e-04
Epoch 8/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 142s 928ms/step - accuracy: 1.0000 - loss: 1.2176e-04
Epoch 9/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 94s 910ms/step - accuracy: 1.0000 - loss: 8.9552e-05
Epoch 10/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 141s 901ms/step - accuracy: 1.0000 - loss: 6.1933e-05


In [11]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

In [12]:
validation_batches = val_data.batch(32)

In [13]:
model.fit(train_batches, epochs=10,
          validation_data=validation_batches)

Epoch 1/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 102s 992ms/step - accuracy: 1.0000 - loss: 4.9098e-05 - val_accuracy: 0.8672 - val_loss: 2.9224
Epoch 2/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 102s 984ms/step - accuracy: 1.0000 - loss: 3.0692e-05 - val_accuracy: 0.8672 - val_loss: 3.0007
Epoch 3/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 100s 971ms/step - accuracy: 1.0000 - loss: 3.1893e-05 - val_accuracy: 0.8672 - val_loss: 3.0658
Epoch 4/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 142s 975ms/step - accuracy: 1.0000 - loss: 2.6731e-05 - val_accuracy: 0.8672 - val_loss: 3.1667
Epoch 5/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 100s 973ms/step - accuracy: 1.0000 - loss: 1.9229e-05 - val_accuracy: 0.8672 - val_loss: 3.1907
Epoch 6/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 142s 972ms/step - accuracy: 1.0000 - loss: 1.6814e-05 - val_accuracy: 0.8672 - val_loss: 3.2783
Epoch 7/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 100s 971ms/step - accuracy: 1.0000 - loss: 1.2930e-05 - val_accuracy: 0.8672 - val_loss: 3.3296
Epoch 8/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 143s 976

# 특정 버전의 데이터셋 로드하기

In [14]:
data, info = tfds.load("horses_or_humans:3.0.0", with_info=True)